name: Unit tests
description: Runs unit tests and uploads code coverage results.

runs:
    using: composite
    steps:
        - name: Install Playwright browsers
          shell: bash
          run: pnpm playwright-install

        - name: Run unit tests
          shell: bash
          run: pnpm --filter @dnd-mapp/realm test-ci

        - name: Upload code coverage
          uses: actions/upload-code-coverage@abb5995db9e0199b0e2bb9dbd136fce4cb1ec4d3 # v1.3.0
          with:
              file: coverage/apps/realm/cobertura-coverage.xml
              language: javascript
              label: realm
