export const EnvironmentVariables = {
    AUTH_SERVER_HOST: 'AUTH_SERVER_HOST',
    AUTH_SERVER_PORT: 'AUTH_SERVER_PORT',

    AUTH_DB_HOST: 'AUTH_DB_HOST',
    AUTH_DB_PORT: 'AUTH_DB_PORT',
    AUTH_DB_SCHEMA: 'AUTH_DB_SCHEMA',
    AUTH_DB_USER: 'AUTH_DB_USER',
    AUTH_DB_PASSWORD: 'AUTH_DB_PASSWORD',
} as const;
