name: CI
description: Runs Continuous Integration checks
runs:
    using: composite
    steps:
        - name: Set up tools
          uses: ./.github/actions/setup-tools

        - name: Check formatting
          shell: bash
          run: pnpm exec nx format:check --base "${{ env.NX_BASE }}" --head "${{ env.NX_HEAD }}"

        - name: Run linting
          shell: bash
          run: pnpm exec nx affected -t lint --base "${{ env.NX_BASE }}" --head "${{ env.NX_HEAD }}"

        - name: Compile code
          shell: bash
          run: pnpm exec nx affected -t build --base "${{ env.NX_BASE }}" --head "${{ env.NX_HEAD }}"

        - name: Run tests
          shell: bash
          run: |
              pnpm playwright:install
              pnpm exec nx affected -t test --base "${{ env.NX_BASE }}" --head "${{ env.NX_HEAD }}"
