name: Sync DockerHub README

on:
    push:
        branches:
            - main
        paths:
            - '.docker/**/README.md'
    workflow_dispatch:

concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

jobs:
    sync:
        name: Sync DockerHub README
        runs-on: ubuntu-22.04
        timeout-minutes: 5
        permissions:
            contents: read
        steps:
            - name: Checkout
              uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3

            - name: Sync realm README
              uses: peter-evans/dockerhub-description@1b9a80c056b620d92cedb9d9b5a223409c68ddfa # v5.0.0
              with:
                  username: ${{ secrets.DOCKERHUB_USERNAME }}
                  password: ${{ secrets.DOCKERHUB_TOKEN }}
                  repository: dndmapp/realm
                  readme-filepath: .docker/realm/README.md
